apiversion: apps/v1
kind: Deployment
metedata:
  name: postgress-deployment
spec:
  replicas: 1
  selector:
    matchLablels:
      component: postgress
  template:
    metedata: 
      labels:
        component: postgress
    spec:
      volumes:
        - name: postgress-storage
          presistentVolumeClaim:
            claimnName: database-persistent-volume-claim
      containers:
        - name: postgress
          image: postgress
          ports:
            - ContainerPort: 5432
          volumeMounts:
            - name: postgress-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgress
        env: 
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: pgpassword
                value: PGPASSWORD